"""empty message

Revision ID: 5f369d408a9a
Revises: 9132e54655d7
Create Date: 2024-05-06 02:01:50.279690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f369d408a9a'
down_revision = '9132e54655d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('sent_to_room_id',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.alter_column('creator_id',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.alter_column('creator_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('sent_to_room_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
