"""empty message

Revision ID: 74c5065f7342
Revises: 954e707894f7
Create Date: 2024-05-06 01:39:42.238224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74c5065f7342'
down_revision = '954e707894f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'sent_to_room_id',
               existing_type=sa.VARCHAR(),
               )
    op.alter_column('room', 'creator_id',
               existing_type=sa.VARCHAR(),
               )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('room', 'creator_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('message', 'sent_to_room_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
