"""initial migration

Revision ID: 954e707894f7
Revises: 
Create Date: 2024-05-04 22:07:07.473037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '954e707894f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('userID', sa.String(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('userID'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('room',
    sa.Column('room_name', sa.String(), nullable=False),
    sa.Column('room_id', sa.String(), nullable=False),
    sa.Column('room_banner', sa.String(), nullable=True),
    sa.Column('creator_id', sa.String(), nullable=True),
    sa.Column('joining_url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['user.userID'], ),
    sa.PrimaryKeyConstraint('room_id')
    )
    op.create_table('association_table',
    sa.Column('left_id', sa.String(), nullable=False),
    sa.Column('right_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['left_id'], ['user.userID'], ),
    sa.ForeignKeyConstraint(['right_id'], ['room.room_id'], ),
    sa.PrimaryKeyConstraint('left_id', 'right_id')
    )
    op.create_table('message',
    sa.Column('message_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message_body', sa.String(), nullable=True),
    sa.Column('sent_to_room_id', sa.String(), nullable=True, back_populates='messages'),
    sa.Column('sent_id', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sent_id'], ['user.userID'], ),
    sa.ForeignKeyConstraint(['sent_to_room_id'], ['room.room_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    op.drop_table('association_table')
    op.drop_table('room')
    op.drop_table('user')
    # ### end Alembic commands ###
